unit HTTP.Types;

interface

const
  HTTP_SUCCESS = 200;
  HTTP_BAD_REQUEST = 400;
  HTTP_UNAUTHORIZED = 401;
  HTTP_NOT_FOUND = 404;
  HTTP_REQUEST_TIMEOUT = 408;
  HTTP_INTERNAL_ERROR = 500;
  HTTP_SERVICE_UNAVAILABLE = 503;
  HTTP_UNKNOWN_ERROR = 520;

  CONTENTTYPE_APPLICATION_JSON = 'application/json';

implementation

end.
